### ISSUE TITLE
Lookup function not working through hiera

### ISSUE THREAD

**Issue by karolina1819** [TraGicCode/tragiccode-azure_key_vault#101]
Hi TraGicCode,

Thank you for writing this module. Unfortunately, I haven't been able to make it work through hiera as expected.

Puppet version: 6.26.0

tragiccode-azure_key_vault version: v3.1.0

Section in hiera.yaml hierarchy:

```
  - name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: qahub-key-vault
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      confine_to_keys:
        - '^azure.*'
        - '^.*_password$'
        - '^password.*'
```

This is the code I've been testing:

```
class infra::akv (
)
{

file { '/opt/akv':
    ensure => 'directory',
}

$password = lookup('azure-secret-password')

file { '/opt/akv/testpass':
  content => $password,
  ensure    => file,
}
}
```

Used like this it gives the output, as expected:

```
root@puppetserver:/etc/puppetlabs/code/environments/infra# puppet agent -t
Info: Using environment 'infra'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Info: Caching catalog for puppetserver
Info: Applying configuration version '12345....'
Notice: /Stage[main]/Infra::Akv/File[/opt/akv/testpass]/content: [diff redacted]
Info: Computing checksum on file /opt/akv/testpass
Info: /Stage[main]/Infra::Akv/File[/opt/akv/testpass]: Filebucketed /opt/akv/testpass to puppet with sum 5c453af9ce37794e697cefd0392dbcf8
Notice: /Stage[main]/Infra::Akv/File[/opt/akv/testpass]/content: changed [redacted] to [redacted]
Notice: Applied catalog in 21.74 seconds
```

Also, file is correctly updated.

But, if used through hiera, with editing data/nodes/puppetserver.yaml file with line:

```
infra::akv::password: "%{lookup('azure-secret-password')}"
```

With manifest then looking like this:

```
class infra::akv (
  $password,
)
{

file { '/opt/akv':
    ensure => 'directory',
}

file { '/opt/akv/testpass':
  content => $password,
  ensure    => file,
}
}
```

Output is:

```
................
Notice: /Stage[main]/Infra::Akv/File[/opt/akv/testpass]/content:
--- /opt/akv/testpass   2023-01-09 09:41:27.076211584 +0000
+++ /tmp/puppet-file20230109-25695-sr98eh       2023-01-09 10:23:20.661981354 +0000
@@ -1 +1 @@
-this_is_secret
\ No newline at end of file
+Sensitive [value redacted]
\ No newline at end of file

Info: Computing checksum on file /opt/akv/testpass
Info: /Stage[main]/Infra::Akv/File[/opt/akv/testpass]: Filebucketed /opt/akv/testpass to puppet with sum 9486ce60ddb022349d8a9e04788da9e8
Notice: /Stage[main]/Infra::Akv/File[/opt/akv/testpass]/content: content changed '{md5}9486ce60ddb022349d8a9e04788da9e8' to '{md5}5c453af9ce37794e697cefd0392dbcf8'
................
```

So, nothing is reducted and literally the string "Sensitive [value redacted]" is written in the file.

Can you help me with this?
