### ISSUE TITLE
multiple vaults via hierra file

### ISSUE THREAD

**Issue by marcelmitto** [TraGicCode/tragiccode-azure_key_vault#123]
This is not a bug - just a feature request if possible :) 
allow to specify multiple vaults via hierra yaml file.

**Comment by TraGicCode** [comment]
Hey @marcelmitto ,

Would you be able to describe in detail how you would expect this to work along with how you would expect this to look like in the hiera.yaml file?

**Comment by powercycleagain** [comment]
A small example from my side. Or Puppet server now search in 5 keyvaults but this gives a lot of underlying 404's. As a workarround it is possible to include the name of the keyvault in the search/secret name. But due to our company policy it is not possible to include the keyvault name in the secret name. It would therefore be ideal if the keyvault name is stripped during the search for the secret. Another nice solution is also welcome.

```
---
lookup_options:
  corp1:
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: 'CORP1'
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      confine_to_keys:
        - '^corp1_.^user_unix_hash$'
  corp2:
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: 'CORP2'
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      confine_to_keys:
        - '^corp2_.^user_unix_hash$'

corp1_user1_unix_hash: "%{alias('azure_key_vault::lookup')}"
corp2_user1_unix_hash: "%{alias('azure_key_vault::lookup')}"

Keyvault secrets:
  corp1:
    user1_unix_hash (secret)
  corp2:
    user2_unix_hash (secret)
```

Search for the users without the keyvault name in the key name.

**Comment by TraGicCode** [comment]
Hey @powercycleagain and @marcelmitto ,

Sorry for getting back to you late. So, you’re saying you would like a feature in the Puppet code where the vault name is included in the secret name, but on the Azure side, the secret name does not include the vault name. This way, you can route secret queries to the appropriate vault where the secret resides?

**Comment by powercycleagain** [comment]
Hi Michael,

Yes that would be great. This saves us a lot of configuration work when using multiple vaults.

**Comment by TraGicCode** [comment]
Hey @powercycleagain and @marcelmitto ,

I'm currently working on a new feature which adds a "strip_from_keys" option.  I believe this will resolve your issue.  Can you review the below draft documentation and let me know if this works for your use-case?

#######

### What is strip_from_keys?

The `strip_from_keys` option allows you to specify one or more patterns to be stripped from the secret name just before looking up the secret in Azure Key Vault. To understand how this is useful, let's walk through an example.

```yaml
- name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: "prod-key-vault"
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      confine_to_keys:
        - '^azure_.*'
```

In the example above, `confine_to_keys` is used to scope certain secrets for lookup in Azure Key Vault, ensuring they are retrieved only when they truly exist there. However, as a side effect, `confine_to_keys` influences the secret name. In this case, the Azure Key Vault named "prod-key-vault" would need to have a secret named "azure_sql_database_password".

To prevent this naming requirement, the `strip_from_keys` option was introduced. It allows you to remove specific patterns from the key just before lookup in Azure Key Vault. Below is an updated example demonstrating how `strip_from_keys` can be applied.

```yaml
- name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: "prod-key-vault"
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      strip_from_keys:
        - '^azure_.*'
      confine_to_keys:
        - '^azure_.*'
```

Now, with `strip_from_keys`, the "azure_*" string pattern is removed from the secret name just before the lookup occurs. This ensures that the system searches for a secret named "sql_database_password" instead of "azure_sql_database_password" in the Azure Key Vault named "prod-key-vault".
