### ISSUE TITLE
Using a key_prefix to allow for node-specific secrets

### ISSUE THREAD

**Issue by sharumpe** [TraGicCode/tragiccode-azure_key_vault#142]
Hello,

I've been experimenting with this module and it's great! Thanks for creating it.
One thing I need to do that wasn't already here is to allow for node-specific keys, similar to the `data/nodes/%{::trusted.certname}.yaml` hierarchy.

I've done a fork that adds a `key_prefix` parameter to the `azure_key_vault::lookup` function. I'm not sure if this is something that others would have an interest in, or how to proceed if so.  I know the code works (there's not much that changed) but I don't have experience with the test code, so I haven't done those.

Use case is like this from `hiera.yaml`:

```yaml
hierarchy:
  - name: 'Azure Key Vault Per-Node Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: secrets
      vault_api_version: '2016-10-01'
      service_principal_credentials: '/etc/puppetlabs/puppet/azure_key_vault_credentials.yaml'
      key_prefix: "%{::trusted.certname}"
      key_replacement_token: '-'
      confine_to_keys:
        - '^secret::.*'
        - '^.*secret$'
        - '^.*password$'
  - name: 'Azure Key Vault Common Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: secrets
      vault_api_version: '2016-10-01'
      service_principal_credentials: '/etc/puppetlabs/puppet/azure_key_vault_credentials.yaml'
      key_replacement_token: '-'
      confine_to_keys:
        - '^secret::.*'
        - '^.*secret$'
        - '^.*password$'
  - name: "Yaml backend"
    paths:
      - "nodes/%{::trusted.certname}.yaml"
      - "osfamilies/%{::os.family}.yaml"
      - "common.yaml"
```

Let me know if you're interested and I can link you to it or whatever works.

Thanks again for this module!

**Comment by TraGicCode** [comment]
Hey @sharumpe ,

Thanks for opening up a github issue! Also, thank you soo much for providing feedback on the module.  I'm glad you are finding it useful.

In regards to your issue, I'm actually working on a new feature in order to resolve #123 and i think this will also solve your problem as well.

My current plan is to add a "strip_from_keys" feature which, if i'm understanding your use-case correctly, should solve your issue as well.  Below is the current draft of my documentation.  Can you give it a read and see if this would indeed resolve your issue?

#####

### What is strip_from_keys?

The `strip_from_keys` option allows you to specify one or more patterns to be stripped from the secret name just before looking up the secret in Azure Key Vault. To understand how this is useful, let's walk through an example.

```yaml
- name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: "prod-key-vault"
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      confine_to_keys:
        - '^azure_.*'
```

In the example above, `confine_to_keys` is used to scope certain secrets for lookup in Azure Key Vault, ensuring they are retrieved only when they truly exist there. However, as a side effect, `confine_to_keys` influences the secret name. In this case, the Azure Key Vault named "prod-key-vault" would need to have a secret named "azure_sql_database_password".

To prevent this naming requirement, the `strip_from_keys` option was introduced. It allows you to remove specific patterns from the key just before lookup in Azure Key Vault. Below is an updated example demonstrating how `strip_from_keys` can be applied.

```yaml
- name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: "prod-key-vault"
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      strip_from_keys:
        - '^azure_.*'
      confine_to_keys:
        - '^azure_.*'
```

Now, with `strip_from_keys`, the "azure_*" string pattern is removed from the secret name just before the lookup occurs. This ensures that the system searches for a secret named "sql_database_password" instead of "azure_sql_database_password" in the Azure Key Vault named "prod-key-vault".

**Comment by sharumpe** [comment]
It's late on a Friday where I'm at, so my brain is basically done, but I _think_ I'm looking at a different scenario.  :)

I think I'm acutally going for the opposite effect - I'm specifically adding a prefix to the key so that I can prepend the node name, e.g. `vmname.contoso.com` to the key, so that I can have both common and node-specific secrets.

Combined with the way you are already normalizing the names, I end up with something like this:
The `mysql::server` module's  parameter `root_password` on machine `vmname.contoso.com` can be provided by setting `hiera.yaml` as I showed in the original post, and adding a secret with this key in the key vault:

`vmname-contoso-com--mysql--server--root-password`

The lookup for `mysql::server::root_password` retrieves that and does what's expected.

**Comment by sharumpe** [comment]
I realized I didn't link my fork in the original post - it's here just in case that helps to show what I'm doing:
https://github.com/sharumpe/tragiccode-azure_key_vault/blob/main/lib/puppet/functions/azure_key_vault/lookup.rb

**Comment by sharumpe** [comment]
Not-tired-Friday follow-up.

The basic gist of what I'm looking to reproduce is the default (for puppet) behavior where we have default/global data in `common.yaml`, and node-specific overrides in `nodes/%{::trusted.certname}.yaml`.

Since we don't want to create another Azure Key Vault for each node, I modified the `lookup.rb` code to add the `key_prefix` function parameter, which just prepends the trusted.certname to the key being looked up.

So when puppet goes to look for `mysql::server::root_password`, it will look in this order, based on the hierarchy in my original post:

- in azure key vault 'secrets' for `vmname.contoso.com--mysql--server--root-password`
- in azure key vault 'secrets' for `mysql--server--root-password`
- in yaml file 'nodes/vmname.contoso.com.yaml' for `mysql::server::root_password`
- in yaml file 'osfamilies/RedHat.yaml' for `mysql::server::root_password`
- in yaml file 'common.yaml' for `mysql::server::root_password`

Sorry for the additional posts - I should have included all this in my original.  :)

**Comment by DennisTerrell** [comment]
I'd like to echo what @sharumpe has proposed. Where this seems to be different than #123 is in adding a unique prefix to use for lookups in a single vault and not stripping anything unique to look in multiple.

**Comment by yakatz** [comment]
I was about to fork this repo and start implementing something similar - I would love to see this feature too.
I am coming from an environment that was using Hashicorp Vault for secrets and that puppet module lets you specify a hierarchy of vault locations to check - since Azure KeyVault doesn't have hierarchies, it would obviously have to use a different style of delimiter for the node information. This looks like it would do what I need too.

**Comment by TraGicCode** [comment]
Hey @sharumpe,

Thanks for the clarification on this! Based on the responses from other GitHub users, this does indeed appear to be a gap that needs to be addressed.

Before I start working on a PR to implement this feature, do you think there are any alternative approaches that might be cleaner for users who are also seeking this? Would something like what @yakatz mentioned be a better alternative to your suggestion?

One of the goals of this module is to minimize the number of calls to Azure Key Vault. This helps prevent TTL issues while also keeping costs down for each call made.

**Comment by TraGicCode** [comment]
> I was about to fork this repo and start implementing something similar - I would love to see this feature too. I am coming from an environment that was using Hashicorp Vault for secrets and that puppet module lets you specify a hierarchy of vault locations to check - since Azure KeyVault doesn't have hierarchies, it would obviously have to use a different style of delimiter for the node information. This looks like it might do some of that.
> 
> For example:
> 
> hierarchy:
>   - name: 'Azure Key Vault Secrets'
>     lookup_key: azure_key_vault::lookup
>     options:
>       vault_name: main
>       vault_api_version: '2016-10-01'
>       service_principal_credentials: '/etc/puppetlabs/puppet/azure.yaml'
>       key_replacement_token: '-'
>       confine_to_keys:
>         - '^azure::.*'
>       strip_from_keys:
>         - 'azure::'
>       mounts:
>         - 'nodes--%{::trusted.certname}--'
>         - 'common--'
> If you wrote `lookup('azure::root_password')`, it would first check for a secret called `nodes--host-fqdn--root-password`, then `common--root-password`.

Hey @yakatz,

It's great to see that you're already using the "strip_from_keys" feature I pushed fairly recently! 

Regarding your proposal, it sounds pretty interesting.

Do you think a feature like "key_prefix" would be insufficient or less flexible from a user's perspective?

**Comment by yakatz** [comment]
> Do you think a feature like "key_prefix" would be insufficient or less flexible from a user's perspective?

`key_prefix` would be less flexible because it would apply to all requests and not give you an easy way to fall back to a default value (like in my example with root passwords).

Personally, in my environment if `key_prefix` were available and not a multiple "mount"/search option, I would add two separate hiera configurations for the same vault, one with the prefix and one without. My environment is small enough to do that without costing too much in Azure fees.

Another option to deal with fees could be that if you want to use the "mount" (or whatever else it is called) option, your user/service-principal/etc needs to have list permissions for the KeyVault and then the list of all available secrets could be cached locally for each run. That would allow the existence of each combination of prefix and secret to be checked against the local list and only fetched if it exists.

**Comment by sharumpe** [comment]
Yes adding to what @yakatz says - my change depended on having multiple full setups in the hierarchy, one for each "place" I want to look at.  I'm new to using Azure for things like this, and did not take the cost into account, though we do limit lookups using the "confine_to_keys" parameter.  If it makes it incur less cost to use only one entry in the hierarchy, I can't argue against that. :)

For most of our use-cases, we're not making explicit `lookup()` calls, instead relying on the implicit hiera parameter lookups that modules do.  Because of that, we wouldn't be making use of the `strip_from_keys` feature, instead using `confine_to_keys` to limit the keys that get looked up in azure_key_vault.

Given that I'm not modifying most of the looked-up key names, I'm not sure how default (unmodified) keys would be looked up with the `mounts` setup, or at least which order they would be looked up in.  After the ones specified in `mounts`?  Personally I prefer configuration to be explicit so there's no question.  Maybe a value of `default` in the mount list?  But whatever works.

Given that, and if I'm understanding @yakatz's use case correctly, I think I would adjust what we're doing in this way:

From this (with my fork's `key_prefix`):

```yaml
hierarchy:
  - name: 'Azure Key Vault Per-Node Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: puppet-linux-secrets
      vault_api_version: '2016-10-01'
      service_principal_credentials: '/etc/puppetlabs/puppet/azure_key_vault_credentials.yaml'
      key_prefix: "%{::trusted.certname}--"
      key_replacement_token: '-'
      confine_to_keys:
        - '^secret::.*'
        - '^.*password$'
        - '^.*secret$'
  - name: 'Azure Key Vault Common Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: puppet-linux-secrets
      vault_api_version: '2016-10-01'
      service_principal_credentials: '/etc/puppetlabs/puppet/azure_key_vault_credentials.yaml'
      key_replacement_token: '-'
      confine_to_keys:
        - '^secret::.*'
        - '^.*password$'
        - '^.*secret$'
  - name: "Yaml backend"
    paths:
      - "nodes/%{::trusted.certname}.yaml"
      - "osfamilies/%{::os.family}.yaml"
      - "common.yaml"
```

To this (using the proposed `mounts`):

```yaml
hierarchy:
  - name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: puppet-linux-secrets
      vault_api_version: '2016-10-01'
      service_principal_credentials: '/etc/puppetlabs/puppet/azure_key_vault_credentials.yaml'
      key_replacement_token: '-'
      confine_to_keys:
        - '^secret::.*'
        - '^.*password$'
        - '^.*secret$'
      mounts:
        - "%{::trusted.certname}--"
        - "default"
  - name: "Yaml backend"
    paths:
      - "nodes/%{::trusted.certname}.yaml"
      - "osfamilies/%{::os.family}.yaml"
      - "common.yaml"
```
