### ISSUE TITLE
(Feature) Add ability to optionally configure a lookup hierarchy

### ISSUE THREAD

**Issue by TraGicCode** [TraGicCode/tragiccode-azure_key_vault#146]
# Problem Statement

Currently, there is no way to allow node-specific secrets similar to how the YAML backend works in Puppet. This issue was brought to my attention through GitHub issue #142.

# Proposal

Implement the ability to configure a custom "hierarchy" in which lookups can be performed to support node-specific secrets.

# Key Considerations

### Performance/Cost

The following key considerations must be taken into account for the implementation of this feature:

1. Reduce costs for large environments.
2. Keep catalog compilation/runs fast.
3. Reduce the rate of hitting rate limits.

**Note: Currently, there is a maximum of 2,000 lookups every 10 seconds allowed against a Key Vault (Standard Tier) and 4,000 lookups every 10 seconds allowed against a Key Vault (Premium Tier).**

### Alternative to other usage

This is not meant to replace or deprecate the current functionality of Hiera in this module. Instead, it's meant to be another way in which this module can be used if more flexibility is needed.

# Proposed Solution

```yaml
  - name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: secrets-vault
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      prefixes: 
        - nodes--%{trusted.hostname}--
        - common--
      confine_to_keys:
        - '^azure_.*'
```

**Comment by yakatz** [comment]
Looks good to me

**Comment by TraGicCode** [comment]
I did take a look at using YAML Anchors in aliases and it appears this "could" work if a new option was added called `key_lookup_template`.  I don't really like this approach because it feels complex/clunky but i did want to leave it here as a note for others in the future ( and for myself! ).

I also didn't test and am not sure if hiera.yaml properly works with anchors and aliases.

With anchors and alises

```yaml
version: 5
defaults:
  datadir: data
  data_hash: yaml_data
azure_key_vault_defaults:
  lookup_key: 'azure_key_vault::lookup'
  options:
    vault_api_version: '2016-10-01'
    service_principal_credentials: /etc/puppetlabs/puppet/azure_key_vault_credentials.yaml
    key_replacement_token: '-'
    key_lookup_template: ''
    confine_to_keys:
      - '^azure_*'
hierarchy:
  - name: Azure Key Vault Per-Node Secrets
    lookup_key: 'azure_key_vault::lookup'
    options:
      key_lookup_template: 'nodes--%{trusted.hostname}--' # overrides `key_lookup_template` from `azure_key_vault_defaults`
  - name: Azure Key Vault Common Secrets
    lookup_key: 'azure_key_vault::lookup'
    options:
      vault_name: secrets # overrides `vault_name` from `azure_key_vault_defaults`
  - name: Yaml backend
    paths:
      - 'nodes/%{::trusted.certname}.yaml'
      - 'osfamilies/%{::os.family}.yaml'
      - common.yaml

```

This is what the above expanded form of the anchors and aliases would result in

```yaml
version: 5
defaults:
  datadir: data
  data_hash: yaml_data

hierarchy:
  - name: Azure Key Vault Per-Node Secrets
    lookup_key: 'azure_key_vault::lookup'
    options:
      vault_api_version: '2016-10-01'
      service_principal_credentials: /etc/puppetlabs/puppet/azure_key_vault_credentials.yaml
      key_replacement_token: '-'
      key_lookup_template: 'nodes--%{trusted.hostname}--'
      confine_to_keys:
        - '^azure_*'

  - name: Azure Key Vault Common Secrets
    lookup_key: 'azure_key_vault::lookup'
    options:
      vault_api_version: '2016-10-01'
      service_principal_credentials: /etc/puppetlabs/puppet/azure_key_vault_credentials.yaml
      key_replacement_token: '-'
      key_lookup_template: ''
      confine_to_keys:
        - '^azure_*'
      vault_name: secrets

  - name: Yaml backend
    paths:
      - 'nodes/%{::trusted.certname}.yaml'
      - 'osfamilies/%{::os.family}.yaml'
      - common.yaml

```

**Comment by TraGicCode** [comment]
Hey @sharumpe ,

I actually messed up on the above example using YAML aliases and anchors.   This has been fixed.

> Your proposed solution with the “prefixes” looks great and gets me the ability to do what we need to do. No need to delve into the extra work for the key_lookup_prefix bit.

Got it! thanks

> I’m assuming that the order that the prefixes are listed in will be the order they’re searched in? If so that’s perfect. Thanks!

Yep, this is how the yaml backend works and how other puppet modules are doing it.

**Comment by yakatz** [comment]
I think the anchors solution would be unnecessarily complex.

The only other change I could think of would be to allow the key name to be inserted anywhere in the string instead of only a prefix, but I don't think that is necessary.

```yaml
    searches:
        # Prepend looked-up value instead of append (using string replacement KEY)
        - KEY--nodes--%{trusted.hostname}
        - KEY--common
```

**Comment by TraGicCode** [comment]
Hey @sharumpe and @yakatz ,

I should have this feature completed by end of next week. Will post back here once the PR is ready to go.

**Comment by TraGicCode** [comment]
hey @sharumpe and @yakatz ,

Can both of you give the below PR a spin? it should be pretty much code complete.  Please let me know if you identify any bugs so i can write a unit test to resolve the issue.

https://github.com/TraGicCode/tragiccode-azure_key_vault/pull/147

**Comment by sharumpe** [comment]
I'm closing up another task right now, but I'll give this a shot in the next hour or two.

**Comment by sharumpe** [comment]
I've tested this out using the following:

```yaml
  - name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: puppet-linux-secrets
      vault_api_version: '2016-10-01'
      service_principal_credentials: '/etc/puppetlabs/puppet/azure_key_vault_credentials.yaml'
      key_replacement_token: '-'
      confine_to_keys:
        - '^secret::.*'
        - '^.*password$'
        - '^.*secret$'
      prefixes:
        - "%{::trusted.certname}--"
        - ""
```

I was able to retrieve the secrets the same way as I had been doing previously.  Specifically, this means the node-specific lookup worked, overriding the not-node-specific one.  I also tested not-node-specific lookups (the `- ""`) and that worked as expected, as well.  I think this looks good, at least for the types of things I do.

Thanks much!
