### ISSUE TITLE
(Feature) Add ability for prefixes to cache list of secrets in given vault to improve speed and reduce lookups to azure.

### ISSUE THREAD

**Issue by TraGicCode** [TraGicCode/tragiccode-azure_key_vault#149]
## Problem Statement

Currently, when using the new `prefixes` option, there could potentially be a large number of lookups to Azure Key Vault as the prefix hierarchy is being searched. This can reduce catalog compilation time and increase Azure costs in large environments.

## Proposal

Add an option that allows the Hiera lookup to "list" all secrets in a given vault and cache them, so that lookups **ONLY** occur for secrets that should be in the vault. This was recommended by [@yakatz](https://github.com/TraGicCode/tragiccode-azure_key_vault/issues/142#issuecomment-2740556106). 

I believe this option should be the default, with the ability to turn it off. Making it the default would be considered a breaking change for users.

## Key Considerations

- The credentials being used to query the vault must contain the **"list secrets"** permission on the vault. This is extra setup that the user is expected to perform.

**Proposed Solution**

```yaml
  - name: 'Azure Key Vault Secrets'
    lookup_key: azure_key_vault::lookup
    options:
      vault_name: secrets-vault
      vault_api_version: '2016-10-01'
      metadata_api_version: '2018-04-02'
      key_replacement_token: '-'
      prefixes_disable_listing_secrets_optimization: true # <--- This is the new feature that can be turned off
      prefixes: 
        - nodes--%{trusted.hostname}--
        - common--
      confine_to_keys:
        - '^azure_.*'
```
